const mongoose =require('mongoose');
const marineSchema=new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"user"
    },
    insuranceType:{
        type:String
    },
    registration_no:{
        type:String
    },
    boat_no:{
        type:String
    },
    boat_length:{
        type:String
    },
    boat_width:{
        type:String
    },
    boat_depth:{
        type:String
    },
    gross_tonnage:{
        type:String
    },
    deadweight_tonnage:{
        type:String
    },
    powerOf_engine:{
        type:String
    },
    engine_number:{
        type:String
    },
    passenger_capacity:{
        type:String
    },
    materialOf_hull:{
        type:String
    },
    place_built:{
        type:String
    },
    no_of_engine:{
        type:String
    },
    model_year:{
        type:String
    },
   
    policy_period:{
        type:String
    },
    start_date:{
        type:String
    },
    policy_end_date:{
        type:String
    },
    usage:{
        type:String
    },
    manufacturer:{
        type:String
    },
    model:{
        type:String
    },
    vesselType:{
        type:String
    },
    planId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"vender_policy"
    },
    policy_start_date:{
        type:String
    },
    policy_exp_date:{
        type:String
    },
    duration:{
        type:Number
    },
    policy_fee:{
        type:Number
    },
    policy_number:{
        type:Number
    },
    submission_fee:{
        type:Number
    },
    policyPremium_total:{
        type:Number
    },
    status:{
        type:String,
        default:"Selected"
    },


    
    
},{timestamps:true});
 module.exports = mongoose.model("marine_insurance",marineSchema);